fun main() {
    val sony = TV("Sony", "KD-98ZG9", 98)
    val lg = TV("LG", "OLED88Z29LA", 88)
    val samsung = TV("Samsung", "QE85QN800AU", 85)

    //Вывод информации о созданных телевизорах
    println("Вывод информации о созданных телевизорах:")
    println()
    sony.tvInfo()
    samsung.tvInfo()
    lg.tvInfo()
    Thread.sleep(1000)
    println()

    //Вывод состояния телевизоров
    println("Вывод состояния телевизоров (включен или выключен):")
    println()
    sony.sostoyanieOnOff()
    samsung.sostoyanieOnOff()
    lg.sostoyanieOnOff()
    Thread.sleep(1000)
    println()

    //Проверка включения и выключения телевизоров
    println("Проверка включения и выключения телевизоров:")
    println()
    sony.on()
    samsung.on()
    Thread.sleep(1000)
    println()

    println("Вывод состояния телевизоров (включен или выключен):")
    println()
    sony.sostoyanieOnOff()
    samsung.sostoyanieOnOff()
    lg.sostoyanieOnOff()
    Thread.sleep(1000)
    println()

    //Проверка прибавления и убавления звука
    println("Проверка прибавления и убавления звука:")
    println()
    samsung.pribavlenieZvuka()
    Thread.sleep(1000)
    println()
    samsung.ubavlenieZvuka()
    Thread.sleep(1000)
    println()
    samsung.ubavlenieZvuka()
    Thread.sleep(1000)
    println()
    sony.pribavlenieZvuka()
    Thread.sleep(1000)
    println()
    sony.pribavlenieZvuka()
    Thread.sleep(1000)
    println()
    sony.pribavlenieZvuka()
    Thread.sleep(1000)
    println()
    sony.pribavlenieZvuka()
    Thread.sleep(1000)
    println()
    sony.pribavlenieZvuka()
    Thread.sleep(1000)
    println()
    sony.pribavlenieZvuka()
    Thread.sleep(1000)
    println()

    println("Вывод состояния звука телевизоров:")
    println()
    sony.sostoyanieZvuka()
    lg.sostoyanieZvuka()
    samsung.sostoyanieZvuka()
    Thread.sleep(1000)
    println()

    lg.pribavlenieZvuka()
    Thread.sleep(1000)
    println()
    lg.ubavlenieZvuka()
    Thread.sleep(1000)
    println()

    println("Вывод состояния звука телевизоров:")
    println()
    sony.sostoyanieZvuka()
    lg.sostoyanieZvuka()
    samsung.sostoyanieZvuka()
    Thread.sleep(1000)
    println()

    //Выключение телевизоров
    println("Выключение телевизоров:")
    println()
    sony.off()
    lg.off()
    samsung.off()
    Thread.sleep(1000)
    println()

    //Вывод состояния телевизоров
    println("Вывод состояния телевизоров (включен или выключен):")
    println()
    sony.sostoyanieOnOff()
    lg.sostoyanieOnOff()
    samsung.sostoyanieOnOff()
    Thread.sleep(1000)
    println()

    //Контрольный вывод списка каналов для каждого телевизора
    println("Контрольный вывод списка каналов для каждого телевизора:")
    println()
    sony.tvInfo()
    println()
    sony.vivodSpiskaKanalov()
    println()

    lg.tvInfo()
    println()
    lg.vivodSpiskaKanalov()
    println()

    samsung.tvInfo()
    println()
    samsung.vivodSpiskaKanalov()
    Thread.sleep(1000)
    println()

    //Проверка выбора каналов вверх или вниз
    println("Проверка выбора каналов вверх или вниз:")
    println()
    sony.pereklyuchenieKanalaVverh()
    Thread.sleep(1000)
    println()
    sony.pereklyuchenieKanalaVniz()
    Thread.sleep(1000)
    println()
    sony.pereklyuchenieKanalaVniz()
    Thread.sleep(1000)
    println()
    sony.pereklyuchenieKanalaVniz()
    Thread.sleep(1000)
    println()
    sony.pereklyuchenieKanalaVniz()
    Thread.sleep(1000)
    println()
    lg.pereklyuchenieKanalaVverh()
    Thread.sleep(1000)
    println()
    lg.pereklyuchenieKanalaVverh()
    Thread.sleep(1000)
    println()
    lg.pereklyuchenieKanalaVverh()
    Thread.sleep(1000)
    println()
    lg.pereklyuchenieKanalaVverh()
    Thread.sleep(1000)
    println()
    lg.pereklyuchenieKanalaVverh()
    Thread.sleep(1000)
    println()
    lg.pereklyuchenieKanalaVverh()
    Thread.sleep(1000)
    println()
    lg.pereklyuchenieKanalaVverh()
    Thread.sleep(1000)
    println()
    lg.pereklyuchenieKanalaVverh()
    Thread.sleep(1000)
    println()

    //Вывод состояния телевизоров
    println("Вывод состояния телевизоров (включен или выключен):")
    println()
    sony.sostoyanieOnOff()
    lg.sostoyanieOnOff()
    samsung.sostoyanieOnOff()
    Thread.sleep(1000)
    println()

    //Вывод состояния выбранных каналов
    println("Вывод состояния выбранных каналов:")
    println()
    sony.vivodKanala()
    lg.vivodKanala()
    samsung.vivodKanala()
    Thread.sleep(1000)
    println()

    //Проверка выбора канала вручную
    println("Проверка выбора канала вручную:")
    println()
    sony.perekluchenieKanalaVruchnuyu()
    println()
    Thread.sleep(1000)
    lg.perekluchenieKanalaVruchnuyu()
    println()
    Thread.sleep(1000)
    samsung.perekluchenieKanalaVruchnuyu()
    println()
    Thread.sleep(1000)

    //Вывод состояния выбранных каналов
    println("Вывод состояния выбранных каналов:")
    println()
    sony.vivodKanala()
    lg.vivodKanala()
    samsung.vivodKanala()
    Thread.sleep(1000)
    println()

    //Вывод состояния телевизоров
    println("Вывод состояния телевизоров (включен или выключен):")
    println()
    sony.sostoyanieOnOff()
    lg.sostoyanieOnOff()
    samsung.sostoyanieOnOff()
    Thread.sleep(1000)
}